version: "3.1"
services:
   app:
      container_name: application
      build: .
      environment:
         NODE_ENV: development
         DATABASE_URL: postgres://user:pass@database:5432/apidb
      ports:
         - "3000:3000"
      links:
         - "db:database"
   db:
      container_name: database
      image: postgres
      ports:
         - "8001:5432"
      environment:
         POSTGRES_USER: user
         POSTGRES_PASSWORD: pass
         POSTGRES_DB: apidb
   admin:
      container_name: adminer
      image: adminer
      restart: always
      depends_on:
         - db
      ports:
         - 8080:8080
